// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpIphone: typeof import('~icons/ep/iphone')['default']
    IIcomoonFreeCodepen: typeof import('~icons/icomoon-free/codepen')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IPhEyeClosedBold: typeof import('~icons/ph/eye-closed-bold')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Tabs: typeof import('./components/Tabs/index.vue')['default']
    TabsItem: typeof import('./components/Tabs/TabsItem.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
