// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    IGisSearchAttribtues: typeof import('~icons/gis/search-attribtues')['default']
    IIconParkOutlinePeopleSpeak: typeof import('~icons/icon-park-outline/people-speak')['default']
    IPhFolderNotchOpen: typeof import('~icons/ph/folder-notch-open')['default']
    IPhQuestionThin: typeof import('~icons/ph/question-thin')['default']
    ISystemUiconsWrite: typeof import('~icons/system-uicons/write')['default']
    ITeenyiconsDoubleCaretRightOutline: typeof import('~icons/teenyicons/double-caret-right-outline')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Tabs: typeof import('./components/Tabs/index.vue')['default']
    TabsItem: typeof import('./components/Tabs/TabsItem.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
